### ISSUE TITLE
Dynamic replacements

### ISSUE THREAD

**Issue by rmpestano** [rmpestano/dbunit-rules#20]
Currently we have fixed replacements like 

```
tweet:
  - id: "1"
    content: "dbunit rules!"
    date: "[DAY,NOW]"
    user_id: 1
  - id: "2"
    content: "dbunit rules!"
    date: "[DAY,YESTERDAY]"
    user_id: 1
  - id: "3"
    content: "dbunit rules!"
    date: "[DAY,TOMORROW]"
    user_id: 1
```

and only these keywords are replaced by [DateTimeReplacer](https://github.com/rmpestano/dbunit-rules/blob/master/core/src/main/java/com/github/dbunit/rules/replacer/DateTimeReplacer.java).

Dynamic replacements are possible by invoking a script language using jsr 223, more [details here](https://developer.jboss.org/thread/194717?start=0&tstart=0).
